### ISSUE TITLE
Interface de statistiques

### ISSUE THREAD

**Issue by bynicodevelop** [bynicodevelop/atrapio#32]
Créer une nouvelle vue qui permettra l'intégration de statistiques (issus d'un script de tracking).

Voici les détails à faire figurer sur la vue.

![CleanShot 2021-12-13 at 07 10 42@2x](https://user-images.githubusercontent.com/32275195/145763020-f0fa5aa7-df73-44fe-aa46-7aa44f2286ea.png)

Contraintes : 

- Aller à l’essentiel (car il est très fortement possible que ça évolue)
- Utiliser le material design proposer par Flutter
- Pas de mise en forme autre que le material design (Le design viendra beaucoup plus tard)
- Mettre en place des données en dur (ex : un Map<String, dynamic>) 
(La création de modèle viendra quand j'aurai finalisé les données cotées Firebase)
- Ajouter une route sur le modèle déjà en place. (forcer la route par défaut pour le développement)
- Penser à une mise en forme sommaire pour le Web

**Comment by bynicodevelop** [comment]
Est-il possible de créer un widget "générique" pour les visites ou conversion afin d'avoir la même mise en forme mais des paramètres différents ?

Un peu comme la fonction _page qui a été créé.

Pareil pour la méthode _page faire ne sorte qu'il soit possible de passer des paramètres pour rendre générique cette partie aussi.

**Comment by Bongouade** [comment]
C'est compris
